import type { Animation } from '../../shared/types';
import { getCompleteCss } from './cssFormatting';

/**
 * Generate CSS for all animations combined
 */
export function exportAllAsCSS(animations: Animation[]): string {
  if (animations.length === 0) {
    return '/* No animations found */';
  }

  const header = `/*
 * CSS Animations Export
 * Generated by CSS Weaver
 * Total animations: ${animations.length}
 * Date: ${new Date().toISOString()}
 */

`;

  const sections = animations.map((animation, index) => {
    const separator = index > 0 ? '\n/* ---------------------------------------- */\n\n' : '';
    return separator + getCompleteCss(animation);
  });

  return header + sections.join('\n');
}

/**
 * Download content as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/css'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

/**
 * Generate a filename based on source URL
 */
export function generateFilename(sourceUrl: string | null): string {
  if (!sourceUrl) {
    return 'animations.css';
  }

  try {
    const url = new URL(sourceUrl);
    const domain = url.hostname.replace(/^www\./, '');
    return `${domain}-animations.css`;
  } catch {
    return 'animations.css';
  }
}

/**
 * Copy text to clipboard with fallback
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}
